SMALL_MA = 7
MEDIUM_MA = 25
BIG_MA = 100

WINNING_STOP_LOSS_RETRACE = 0.618
WAVE_THRESHOLD_RETRACEMENT = 0.236
WINNING_STOP_LOSS_THRESHOLD = 0.05
INITIAL_STOP_LOSS = 0.05
VOL_AVG_RATIO = 2.5

CANDLE_HISTORY_SIZE = 10

[BB]
TimePeriod = 20
NbDevDn = 2
NbDevUp = 2

[RSI]
interval=14

[MACD]
short = 12
long = 26
signal = 9
