vSMALL_MA = 7
MEDIUM_MA = 25
BIG_MA = 80

WINNING_STOP_LOSS_RETRACE = 0.5
WAVE_THRESHOLD_RETRACEMENT = 0.236
WINNING_STOP_LOSS_THRESHOLD = 0.01
INITIAL_STOP_LOSS = 0.025

CANDLE_HISTORY_SIZE = 100

[BB]
TimePeriod = 20
NbDevDn = 2
NbDevUp = 2

[RSI]
interval=14

[MACD]
short = 12
long = 26
signal = 9
