# the treshold for buying into a currency. e.g.: The predicted price is 1% above the current candle.close

threshold_buy = 1.00

# the treshold for selling a currency. e.g.: The predicted price is 1% under the current candle.close
threshold_sell = -1.00

# The length of the candle.close price buffer. It's used to train the network on every update cycle.
price_buffer_len = 100

# The learning rate of net
learning_rate = 0.01

# when the price falls up to 4% and the strat indicates to go short, hodl!
hodl_threshold = 0.96

# learning speed
momentum = 0.9
decay = 0.01

#minimum number of prictions until the network is considered 'trained'. History size should be equal
min_predictions = 1000

#enables stoploss function
stoploss_enabled = false

#trigger stoploss 5% under last buyprice
stoploss_threshold = 0.95